// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhogeqccquelhsescbdc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZob2dlcWNjcXVlbGhzZXNjYmRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0NjAxMjksImV4cCI6MjA2MzAzNjEyOX0.zyNSfLSFT-YeLduLBGdlU8fr4MnmgQYIAWQvYHBhMls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);